local RushListCfg ={
[1] = {
['Id'] = 1,
['RankType'] = 1,
['RankId'] = 1,
['StartDay'] = 2,
['StartTime'] = '12:00:00',
['CloseDay'] = 5,
['CloseTime'] = '21:00:00',
['RestDay'] = 6,
['RestTime'] = '21:00:00',
['RankGrade'] = 1,
['Rank'] = {{1,1}},
['Reward'] = {{13150,1},{12135,3},{138,2},{139,2},{2,1000}},
['Banner'] = {'','RankBanner/banner_tower_cn','RankBanner/banner_tower_sale_cn'},
['TitleIcon'] = 'Medal/ic_season_chest05',
['Title'] = {'','LOC_RUSH_LIST_TITLE_TOWER_2','LOC_RUSH_LIST_TITLE_TOWER_3'},
['Desc'] = {'','LOC_RUSH_LIST_DESC_TOWER_2','LOC_RUSH_LIST_DESC_TOWER_3'},
['Corner'] = {'','LOC_RUSH_LIST_CORNER_1','LOC_RUSH_LIST_CORNER_2'},
},
[2] = {
['Id'] = 2,
['RankType'] = 1,
['RankId'] = 1,
['StartDay'] = 2,
['StartTime'] = '12:00:00',
['CloseDay'] = 5,
['CloseTime'] = '21:00:00',
['RestDay'] = 6,
['RestTime'] = '21:00:00',
['RankGrade'] = 2,
['Rank'] = {{2,2}},
['Reward'] = {{12135,2},{138,2},{139,2},{2,500}},
['Banner'] = {'','RankBanner/banner_tower_cn','RankBanner/banner_tower_sale_cn'},
['TitleIcon'] = 'Medal/ic_season_chest04',
['Title'] = {'','LOC_RUSH_LIST_TITLE_TOWER_2','LOC_RUSH_LIST_TITLE_TOWER_3'},
['Desc'] = {'','LOC_RUSH_LIST_DESC_TOWER_2','LOC_RUSH_LIST_DESC_TOWER_3'},
['Corner'] = {'','LOC_RUSH_LIST_CORNER_1','LOC_RUSH_LIST_CORNER_2'},
},
}
return RushListCfg